create database ithub;
use ithub;
create table moviess(movie_id varchar(30),title varchar(30),director_id varchar(30),release_year varchar(30),FOREIGN KEY (movie_id) REFERENCES moviegenres(movie_id));
create table director(director_id varchar(20),director_name varchar(30));
create table genre(genre_id varchar(20) primary key,genre_name varchar(30));
create table moviegenres(movie_id varchar(10) primary key,genre_id varchar(20),FOREIGN KEY (genre_id) REFERENCES genre(genre_id));
insert into moviess values(1,'rrr',11,2022);
insert into moviess values(2,'pushpa',22,2021);
insert into director values(11,'rajamouli');
insert into director values(22,'sukumar');
insert into genre values(111,'action');
insert into genre values(222,'drama');
insert into moviegenres values(1,111);
insert into moviegenres values(2,222);
select distinct moviess.title,director.director_name from moviess join director on moviess.director_id=director.director_id;
select distinct moviess.title,director.director_name,moviess.release_year from moviess left join director on moviess.director_id=director.director_id;
select director.director_name,moviess.title from director left join moviess on director.director_id=moviess.director_id;
select moviess.title,moviess.release_year,director.director_name from moviess right join director on moviess.director_id=director.director_id;
select moviess.title,genre.genre_name from genre join moviegenres on moviegenres.genre_id=genre.genre_id join moviess on moviegenres.movie_id=moviess.movie_id;